program wantop
  use w90_constants, only : dp, eps6
  use w90_parameters
  use w90_io

  use w90_kmesh
  use w90_comms, only : on_root,num_nodes, comms_setup, comms_end, comms_bcast
  use w90_postw90_common
  use w90_get_oper


  implicit none
  integer       :: nkp, len_seedname
  logical       :: have_gamma
  real(kind=dp) :: time0,time1,time2
  character(len=9) :: stat,pos
  logical :: wpout_found, werr_found
  !!! HERE IS MY DECLARATION
  integer cnt_i, cnt_j, cnt_k, r_unit, h_unit, w_unit

  !!! END OF MY DECLARATION

  ! Put some descriptive comments here
  !
  call comms_setup

  library = .false.
  ispostw90 = .true.

  if(on_root) then
     time0=io_time()
     call io_get_seedname
     len_seedname = len(seedname)
  end if
  call comms_bcast(len_seedname,1)
  call comms_bcast(seedname,len_seedname)

  if (on_root) then
     ! If an error file (generated by postw90) exists, I delete it
     ! Note: I do it only for the error file generated from the root node;
     ! If error files generated by other nodes exist, I don't do anything for them
     stdout=io_file_unit()
     open(unit=stdout,file=trim(seedname)//'.wout',ACTION="write", STATUS="replace")
  end if

  ! Read onto the root node all the input parameters from seendame.win,
  ! as well as the energy eigenvalues on the ab-initio q-mesh from seedname.eig
  !
  if(on_root) then
       call param_read
       call param_postw90_write
       time1=io_time()
       write(stdout,'(1x,a25,f11.3,a)')&
            'Time to read parameters  ',time1-time0,' (sec)'

       if(.not.effective_model) then
          ! Check if the q-mesh includes the gamma point
          !
          have_gamma=.false.
          do nkp=1,num_kpts
             if (all(abs(kpt_latt(:,nkp))<eps6)) have_gamma=.true.
          end do
          if(.not. have_gamma) write(stdout,'(1x,a)')&
               'Ab-initio does not include Gamma. Interpolation may be incorrect!!!'
          !
          ! Need nntot, wb, and bk to evaluate WF matrix elements of
          ! the position operator in reciprocal space. Also need
          ! nnlist to compute the additional matrix elements entering
          ! the orbital magnetization
          !
          call kmesh_get
          time2=io_time()
          write(stdout,'(1x,a25,f11.3,a)')&
               'Time to get kmesh        ',time2-time1,' (sec)'
       endif

       ! GP, May 10, 2012: for the moment I leave this commented
       ! since we need first to tune that routine so that it doesn't
       ! print the memory information related to wannier90.x.
       ! Note that the code for the memory estimation for the
       ! Boltzwann routine is already there.
       !       call param_memory_estimate
  end if

  ! We now distribute a subset of the parameters to the other nodes
  !
  call wanint_param_dist

  if(.not.effective_model) then
     !
     ! Read files seedname.chk (overlap matrices, unitary matrices for
     ! both disentanglement and maximal localization, etc.)
     !
     if(on_root) call param_read_chkpt()
     !
     ! Distribute the information in the um and chk files to the other nodes
     !
     ! Ivo: For interpolation purposes we do not need u_matrix_opt and
     !      u_matrix separately, only their product v_matrix, and this
     !      is what is distributed now
     !
     call wanint_data_dist
  end if

  ! Read list of k-points in irreducible BZ and their weights
  !
  ! Should this be done on root node only?
  !
  if(wanint_kpoint_file) call wanint_get_kpoint_file

  ! Setup a number of common variables for all interpolation tasks
  !
  call wanint_setup

  if(on_root) then
     time1=io_time()
     write(stdout,'(/1x,a25,f11.3,a)')&
          'Time to read and process .chk    ',time1-time2,' (sec)'
  endif

  ! ---------------------------------------------------------------
  ! HERE IS MY PROGRAM
  ! ---------------------------------------------------------------
  !
  call get_AA_R
  call get_HH_R
  r_unit = io_file_unit()
  open(r_unit, file='rr.dat', ACTION="write", STATUS="replace")
  write(r_unit, '(I3)') num_wann
  write(r_unit, '(I7)') nrpts
  do cnt_i=1,nrpts
    do cnt_j=1,num_wann
      do cnt_k=1,num_wann
        write(r_unit,'(I2," ",I2," ",I2)',advance='no')&
        irvec(1,cnt_i),irvec(2,cnt_i),irvec(3,cnt_i)
        write(r_unit,'(" ",I2," ",I2)',advance='no') cnt_k,cnt_j
        write(r_unit,'(F17.10," ",F17.10," ",F17.10," ",F17.10," ",F17.10," ",F17.10)')&
        AA_R(cnt_k,cnt_j,cnt_i,1),AA_R(cnt_k,cnt_j,cnt_i,2),AA_R(cnt_k,cnt_j,cnt_i,3)
      end do
    end do
  end do
  close(r_unit)
  h_unit = io_file_unit()
  open(h_unit, file='hr.dat', ACTION="write", STATUS="replace")
  write(h_unit, '(I3)') num_wann
  write(h_unit, '(I7)') nrpts
  do cnt_i=1,nrpts
    do cnt_j=1,num_wann
      do cnt_k=1,num_wann
        write(h_unit,'(I2," ",I2," ",I2)',advance='no')&
        irvec(1,cnt_i),irvec(2,cnt_i),irvec(3,cnt_i)
        write(h_unit,'(" ",I2," ",I2)',advance='no') cnt_k,cnt_j
        write(h_unit,'(F17.10," ",F17.10)')&
        HH_R(cnt_k,cnt_j,cnt_i)
      end do
    end do
  end do
  close(h_unit)
  w_unit = io_file_unit()
  open(w_unit, file='weight.dat', ACTION="write", STATUS="replace")
  write(w_unit, *) ndegen
  close(w_unit)
  !!! END OF MY PROGRAM

  ! I put a barrier here before calling the final time printing routines,
  ! just to be sure that all processes have arrived here.
  call comms_barrier
  if(on_root) then
     write(stdout,'(/,1x,a25,f11.3,a)')&
          'Total Execution Time     ',io_time(),' (sec)'
     if (timing_level>0) call io_print_timings()
     write(stdout,*)
     write(stdout,'(/,1x,a)') 'All done: wantop exiting'
     close(stdout)
  end if

  call comms_end

end program wantop